[env]
TERM = "xterm-256color"
[window]
padding.x=10
padding.y=10

decorations = "Buttonless"

#opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000
